### ISSUE TITLE
Use pop-tools for regions fed to zonal mean tool

### ISSUE THREAD

**Issue by mnlevy1981** [marbl-ecosys/cesm2-marbl#23]
`pop-tools` provides a mechanism to divvy the Southern Ocean among the Atlantic, Pacific, and Indian Oceans so that zonal means for those three extend beyond 40 S. We want that in the nutrient plots (and @kristenkrumhardt would like that feature for her work as well)

**Comment by klindsay28** [comment]
@mnlevy1981 , my `za` program has a command line argument for the file that `REGION_MASK` is read from. The file `/glade/p/cgd/oce/people/klindsay/oldcgdoce/REGION_MASK/new_REGION_MASK_gx1v6.nc` has 3 regions: Pacific, Indian, Atlantic. These regions extend to the Antarctic coast, and the Atlantic includes POP's Arctic, Lab Sea, .... This might suite your needs. Marginal seas are omitted, so don't worry that this is gx1v6 instead of gx1v7 (whose only difference is that the Caspian is omitted in gx1v7).

**Comment by mnlevy1981** [comment]
That is very useful, thanks! I was envisioning an option in [`zonal_means_via_fortran()`](https://github.com/marbl-ecosys/cesm2-marbl/blob/master/notebooks/utils.py#L6) but hadn't taken the time to look at how to actually implement that option. Using your `new_REGION_MASK_gx1v6.nc` when requested sounds like exactly what I need, with minimal work on my end.
