### ISSUE TITLE
Table of globally-integrated fluxes

### ISSUE THREAD

**Issue by matt-long** [marbl-ecosys/cesm2-marbl#6]
- Net primary production (PgC/yr) 
- Diatom primary production (%) 
- Sinking POC at 100 m (PgC/yr) 
- Sinking CaCO3 at 100 m (PgC/yr) 
- Rain ratio (CaCO3/POC) 100 m 
- Nitrogen fixation (TgN/yr) 
- Nitrogen deposition (TgN/yr) 
- Denitrification (TgN/yr)
- N cycle imbalance = deposition + fixation - denitrification (TgN/yr)
- Air–sea CO2 flux (PgC yr21)
- Mean ocean oxygen (mmol/m^3)
- Volume where O2 <80 mmol/m^3 (10^15 m^3)
- Volume where O2 <60 mmol/m^3 (10^15 m^3)
- Volume where O2 <5 mmol/m^3  (10^15 m^3)

**Comment by mnlevy1981** [comment]
@matt-long where can I find conversion factors for things like nitrogen deposition and denitrification? POP has both of those quantities in `mol` rather than `g` (I'm using `metpy.units` for conversion, but these specific values are beyond what it can handle).

Also, I'm having trouble finding some of these quantities in the CESM1 run -- do they need to be computed from other variables, or should I omit some values from the CESM1 historical column?
